apiVersion: v1
kind: Service
metadata:
  name: python-crypto
spec:
  selector:
    app.kubernetes.io/name: python-crypto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
